### ISSUE TITLE
Support Android Symbol Uploads

### ISSUE THREAD

**Issue by bobbyg603** [BugSplat-Git/bugsplat-unreal#37]
Use the binaries from https://github.com/BugSplat-Git/symbol-upload/releases to upload Android `.so` file

### Tasks

- [ ] Create Android symbol upload script that uploads unstripped intermediate `.so` files (eg `{{gameRootDir}}/Binaries/Android/MyUnrealCrasher_Symbols_v1`)
- [ ] Add symbol upload build step
- [ ] Re-enable Android symbol upload checkbox in UI

**Comment by bobbyg603** [comment]
This is outdated, we decided to dump the symbols just-in-time instead of uploading them to a separate endpoint.

**Comment by bobbyg603** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unreal Android Symbols](https://trello.com/c/ijHca554/32-unreal-android-symbols)

**Comment by bobbyg603** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unreal Android Symbols](https://trello.com/c/ijHca554/32-unreal-android-symbols)
